{% set version = "1.1.1.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dygraphs
  version: {{ version|replace("-", "_") }}

source:
  fn: dygraphs_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/dygraphs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dygraphs/dygraphs_{{ version }}.tar.gz
  sha256: c3d331f30012e721a048e04639f60ea738cd7e54e4f930ac9849b95f0f005208

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-htmltools >=0.3.5
    - r-htmlwidgets >=0.6
    - r-magrittr
    - r-xts >=0.9_7
    - r-zoo >=1.7_10
  run:
    - r-base
    - r-htmltools >=0.3.5
    - r-htmlwidgets >=0.6
    - r-magrittr
    - r-xts >=0.9_7
    - r-zoo >=1.7_10

test:
  commands:
    - $R -e "library('dygraphs')"           # [not win]
    - "\"%R%\" -e \"library('dygraphs')\""  # [win]

about:
  home: https://github.com/rstudio/dygraphs
  license: MIT
  summary: An R interface to the 'dygraphs' JavaScript charting library (a copy of which is included in the package). Provides rich facilities for charting time-series data in R, including highly configurable series- and axis-display and interactive features like zoom/pan and series/point highlighting.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
