travis:
  secure:
    BINSTAR_TOKEN: gYEUAe3vBcTI1S2sGBxyr6OkCmwiHAf81EhmGQhs/WIi/JYpXukYPROkjVWu+xZYDpVc859zpXeKDYSCNTtcgw3fvc2T3muhMckVAb0XRSdq+xHPivKvUn4g6JUR9fBH5Xuta58NsXbVloXvOjInTVxJrdG8YU0KJbz6S6RAuWhCSOLHA9o/0++f3GIQh1Y1Gd34tFM5kh9IlDD9e4ATX2v99o2qtmRzmys+9DnMwLsj7Tt1fdyKl13LD2jmH0w9ZlEXvLEAczC/BubV2aZqEZaQMQgIH5hfRLMm5PU4epSglVWDMJ/s8Vb5Q0FLjvewrVXe0n5wI/+02BVDOqKQfRukiYSMjH33JMd7nyFfPulG7kocfIzJDAgC8274we4MOUl+DswGRMgCCqDFQ3EfU2UmGvpcGNqDaetohdV5T9p4FNCKIKT29KhiBZpt8dHSwpRzZQWDTUlk7Dp/8poPUtv2bZlWfihJr/R4q/gKDS7Xs4eGTU+CfvoQfUESgDg0ak4np3vREghVnKs3Z4ivTJIM3L70LMQUXl/P5D6yAESbA5j/sRItLrSOI6bSk3ALeNqwqAcGbVFYOZAy4Y1PuNPE5/WQsjH0s2Z5+LZJmy+Sij2Uy/LHmcWRk5NiOGtuFs5klzqV3Ht8SgpMcgX6RiPIu+ORrhxSXkLIxpt6R/s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
